# Generated by Django 4.2.11 on 2024-04-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="max_per_order",
            field=models.IntegerField(default=3),
        ),
    ]
